
INSERT INTO equipos (id, nombre, ciudad, torneo_id, escudoURL) VALUES
(97, 'Leeds United', 'Leeds', 2, 'https://upload.wikimedia.org/wikipedia/en/0/05/Leeds_United_F.C._logo.svg'),
(98, 'Sheffield United', 'Sheffield', 2, 'https://upload.wikimedia.org/wikipedia/en/3/3e/Sheffield_United_FC_logo.svg'),
(99, 'Burnley', 'Burnley', 2, 'https://upload.wikimedia.org/wikipedia/en/0/02/Burnley_F.C._Logo.svg'),
(100, 'Sunderland', 'Sunderland', 2, 'https://upload.wikimedia.org/wikipedia/en/6/60/Logo_Sunderland.svg'),
(101, 'West Bromwich Albion', 'West Bromwich', 2, 'https://upload.wikimedia.org/wikipedia/en/8/8b/West_Bromwich_Albion.svg'),
(102, 'Blackburn Rovers', 'Blackburn', 2, 'https://upload.wikimedia.org/wikipedia/en/0/0f/Blackburn_Rovers.svg'),
(103, 'Middlesbrough', 'Middlesbrough', 2, 'https://upload.wikimedia.org/wikipedia/en/2/2c/Middlesbrough_FC_crest.svg'),
(104, 'Norwich City', 'Norwich', 2, 'https://upload.wikimedia.org/wikipedia/en/8/8c/Norwich_City.svg'),
(105, 'Bristol City', 'Bristol', 2, 'https://upload.wikimedia.org/wikipedia/en/0/02/Bristol_City_Logo.svg'),
(106, 'Watford', 'Watford', 2, 'https://upload.wikimedia.org/wikipedia/en/e/e2/Watford.svg'),
(107, 'Sheffield Wednesday', 'Sheffield', 2, 'https://upload.wikimedia.org/wikipedia/en/8/8c/Sheffield_Wednesday.svg'),
(108, 'Coventry City', 'Coventry', 2, 'https://upload.wikimedia.org/wikipedia/en/3/31/Coventry_City.svg'),
(109, 'Queens Park Rangers', 'Londres', 2, 'https://upload.wikimedia.org/wikipedia/en/0/0a/Queens_Park_Rangers_crest.svg'),
(110, 'Millwall', 'Londres', 2, 'https://upload.wikimedia.org/wikipedia/en/0/0c/Millwall_FC_crest.svg'),
(111, 'Preston North End', 'Preston', 2, 'https://upload.wikimedia.org/wikipedia/en/1/1f/Preston_North_End_FC.svg'),
(112, 'Oxford United', 'Oxford', 2, 'https://upload.wikimedia.org/wikipedia/en/8/8c/Oxford_United_FC.svg'),
(113, 'Swansea City', 'Swansea', 2, 'https://upload.wikimedia.org/wikipedia/en/3/3c/Swansea_City_AFC_logo.svg'),
(114, 'Stoke City', 'Stoke-on-Trent', 2, 'https://upload.wikimedia.org/wikipedia/en/2/29/Stoke_City_FC.svg'),
(115, 'Cardiff City', 'Cardiff', 2, 'https://upload.wikimedia.org/wikipedia/en/3/3c/Cardiff_City_crest.svg'),
(116, 'Portsmouth', 'Portsmouth', 2, 'https://upload.wikimedia.org/wikipedia/en/5/54/Portsmouth_FC.svg'),
(117, 'Hull City', 'Hull', 2, 'https://upload.wikimedia.org/wikipedia/en/2/20/Hull_City_AFC_logo.svg'),
(118, 'Derby County', 'Derby', 2, 'https://upload.wikimedia.org/wikipedia/en/4/4a/Derby_County_crest.svg'),
(119, 'Luton Town', 'Luton', 2, 'https://upload.wikimedia.org/wikipedia/en/3/3c/LutonTownFC2009.png'),
(120, 'Plymouth Argyle', 'Plymouth', 2, 'https://upload.wikimedia.org/wikipedia/en/4/43/Plymouth_Argyle_FC_logo.svg');
