INSERT INTO equipos (id, nombre, ciudad, torneo_id, escudoURL) VALUES
(143, 'Bodø/Glimt', 'Bodø', 21, 'https://www.glimt.no/_/asset/no.seeds.app.football:00000194b2525600/img/logo/bod/logo.png'),
(144, 'Brann', 'Bergen', 21, 'https://www.brann.no/images/escudo.png'),
(145, 'Bryne FK', 'Bryne', 21, 'https://www.brynefk.no/_img/logo/brynefk-logo.png'),
(146, 'Fredrikstad FK', 'Fredrikstad', 21, 'https://www.fredrikstadfk.no/_img/logo/fredrikstad-logo.png'),
(147, 'HamKam', 'Hamar', 21, 'https://www.hamkam.no/_img/logo/hamkam-logo.png'),
(148, 'Haugesund', 'Haugesund', 21, 'https://www.fkh.no/_img/logo/haugesund-logo.png'),
(149, 'KFUM Oslo', 'Oslo', 21, 'https://www.kfum-kam.no/_img/logo/kfum-oslo-logo.png'),
(150, 'Kristiansund BK', 'Kristiansund', 21, 'https://www.kristiansundbk.no/_img/logo/kristiansund-logo.png'),
(151, 'Molde FK', 'Molde', 21, 'https://www.moldefk.no/_img/logo/molde-logo.png'),
(152, 'Rosenborg BK', 'Trondheim', 21, 'https://www.rosenborg.no/_img/logo/rosenborg-logo.png'),
(153, 'Sarpsborg 08', 'Sarpsborg', 21, 'https://www.sarpsborg08.no/_img/logo/sarpsborg-logo.png'),
(154, 'Stabæk', 'Bekkestua', 21, 'https://www.stabak.no/_img/logo/stabak-logo.png'),
(155, 'Strømsgodset', 'Drammen', 21, 'https://www.sgodset.no/_img/logo/sgodset-logo.png'),
(156, 'Tromsø IL', 'Tromsø', 21, 'https://www.til.no/_img/logo/til-logo.png'),
(157, 'Viking FK', 'Stavanger', 21, 'https://www.viking-fk.no/_img/logo/viking-logo.png'),
(158, 'Vålerenga', 'Oslo', 21, 'https://www.vif.no/_img/logo/vif-logo.png');
