
INSERT INTO equipos (id, nombre, ciudad, torneo_id, escudoURL) VALUES
(121, 'R. Racing Club', 'Santander', 29, 'https://upload.wikimedia.org/wikipedia/en/4/4e/Real_Racing_Club_de_Santander_logo.svg'),
(122, 'SD Huesca', 'Huesca', 29, 'https://upload.wikimedia.org/wikipedia/en/9/9e/SD_Huesca_logo.svg'),
(123, 'Elche CF', 'Elche', 29, 'https://upload.wikimedia.org/wikipedia/en/7/7f/Elche_CF_logo.svg'),
(124, 'CD Mirandés', 'Miranda de Ebro', 29, 'https://upload.wikimedia.org/wikipedia/en/4/4b/CD_Mirandés_logo.svg'),
(125, 'Real Oviedo', 'Oviedo', 29, 'https://upload.wikimedia.org/wikipedia/en/1/1f/Real_Oviedo_logo.svg'),
(126, 'UD Almería', 'Almería', 29, 'https://upload.wikimedia.org/wikipedia/en/f/f1/UD_Almería_logo.svg'),
(127, 'Levante UD', 'Valencia', 29, 'https://upload.wikimedia.org/wikipedia/en/1/11/Levante_UD_logo.svg'),
(128, 'Granada CF', 'Granada', 29, 'https://upload.wikimedia.org/wikipedia/en/e/e5/Granada_CF_logo.svg'),
(129, 'Real Sporting', 'Gijón', 29, 'https://upload.wikimedia.org/wikipedia/en/9/9e/Real_Sporting_de_Gijón_logo.svg'),
(130, 'RC Deportivo', 'La Coruña', 29, 'https://upload.wikimedia.org/wikipedia/en/4/4e/RC_Deportivo_de_La_Coruña_logo.svg'),
(131, 'Real Zaragoza', 'Zaragoza', 29, 'https://upload.wikimedia.org/wikipedia/en/2/2e/Real_Zaragoza_logo.svg'),
(132, 'Cádiz CF', 'Cádiz', 29, 'https://upload.wikimedia.org/wikipedia/en/d/d0/Cádiz_CF_logo.svg'),
(133, 'Albacete BP', 'Albacete', 29, 'https://upload.wikimedia.org/wikipedia/en/5/5b/Albacete_Balompié_logo.svg'),
(134, 'SD Eibar', 'Eibar', 29, 'https://upload.wikimedia.org/wikipedia/en/7/7f/SD_Eibar_logo.svg'),
(135, 'Córdoba CF', 'Córdoba', 29, 'https://upload.wikimedia.org/wikipedia/en/1/1e/Córdoba_CF_logo.svg'),
(136, 'Málaga CF', 'Málaga', 29, 'https://upload.wikimedia.org/wikipedia/en/6/6e/Málaga_CF_logo.svg'),
(137, 'CD Castellón', 'Castellón de la Plana', 29, 'https://upload.wikimedia.org/wikipedia/en/5/5d/CD_Castellón_logo.svg'),
(138, 'Burgos CF', 'Burgos', 29, 'https://upload.wikimedia.org/wikipedia/en/3/3d/Burgos_CF_logo.svg'),
(139, 'CD Eldense', 'Elda', 29, 'https://upload.wikimedia.org/wikipedia/en/4/4b/CD_Eldense_logo.svg'),
(140, 'Racing Club Ferrol', 'Ferrol', 29, 'https://upload.wikimedia.org/wikipedia/en/3/3e/Racing_de_Ferrol_logo.svg'),
(141, 'CD Tenerife', 'Santa Cruz de Tenerife', 29, 'https://upload.wikimedia.org/wikipedia/en/3/3e/CD_Tenerife_logo.svg'),
(142, 'FC Cartagena', 'Cartagena', 29, 'https://upload.wikimedia.org/wikipedia/en/4/4b/FC_Cartagena_logo.svg');
